#!/bin/bash
# This script interactively asks for configuration parameters with defaults.

launch_directory=$1
pipeline_direcory=$2

# Default values
default_singularity_cache_dir="./nfx_singularity_cache"
default_results_dir="./results"
default_work_dir="./nf_work"
default_profile="docker,test"

resolve_path() {
    local dir="$1"
    if [[ "$dir" == /* ]]; then
        echo "$dir"  # Absolute path; use as-is.
    else
        echo "${launch_directory}/${dir}"  # Relative path; prefix with launch_directory.
    fi
}

# Prompt user for input
echo "Please provide the following parameters (press Enter to accept the default value)."

read -p "Singularity Cache Directory [${default_singularity_cache_dir}]: " singularity_cache_dir
singularity_cache_dir=${singularity_cache_dir:-$default_singularity_cache_dir}

read -p "Output Directory [${default_results_dir}]: " results_dir
results_dir=${results_dir:-$default_results_dir}

read -p "Temporary Directory (Cache & intermediate results) [${default_work_dir}]: " work_dir
work_dir=${work_dir:-$default_work_dir}

read -p "Additional Profiles (singularity, docker, test, your_custom_profile) [${default_profile}]: " profile
profile=${profile:-$default_profile}

final_singularity_cache_dir=$(resolve_path "$singularity_cache_dir")
final_results_dir=$(resolve_path "$results_dir")
final_work_dir=$(resolve_path "$work_dir")

# Display selected configuration
echo ""
echo "Configuration Selected:"
echo "  Current Directory: $current_directory"
echo "  Singularity Cache Directory: $singularity_cache_dir"
echo "  Results Directory:           $results_dir"
echo "  Temporary Directory:         $work_dir"
echo "  Additional Profiles:         $profile"



echo "#!/bin/bash" > "$launch_directory/metagear_run.sh"
echo "# Generated by metagear_initialize.sh" >> "$launch_directory/metagear_run.sh"
echo "" >> "$launch_directory/metagear_run.sh"
echo "mkdir -p $final_singularity_cache_dir $final_results_dir $final_work_dir" >> "$launch_directory/metagear_run.sh"
echo "export NXF_SINGULARITY_CACHEDIR=$final_singularity_cache_dir" >> "$launch_directory/metagear_run.sh"
echo "RESULTS_DIR=$target_directory/$results_dir" >> "$launch_directory/metagear_run.sh"
echo "WORK_DIR=$target_directory/$work_dir" >> "$launch_directory/metagear_run.sh"
echo "" >> "$launch_directory/metagear_run.sh"
echo "nextflow run $pipeline_direcory/main.nf -c $launch_directory/metagear_run.config -profile $profile --outdir=$final_results_dir -w $final_work_dir \$@" >> $launch_directory/metagear_run.sh

chmod +x $launch_directory/metagear_run.sh
